### PR TITLE
Declare dependencies that are encapsulated inside shared libraries private

### PR DESCRIPTION
**Pull request by rikdev**

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Does this work if the user sets option zlib:shared=True? (Or any other dependancy)

**Comment by rikdev** [comment]
It works (compiles correctly), but the `imports` section in the `conanfile.txt` does not copy files from these dependencies. For example in this case
```
[requires]
qt/5.12.4@bincrafters/stable

[options]
zlib:shared=True

[imports]
bin, *.dll -> ./bin
lib, *.so* -> ./lib
```
files `libz.so` or `zlib1.dll` will not be copied.
But if the user uses the option `zlib: shared = True`, his file `conanfile.txt` likely looks like this:
```
[requires]
qt/5.12.4@bincrafters/stable
zlib/1.2.11@conan/stable

[options]
zlib:shared=True

[imports]
bin, *.dll -> ./bin
lib, *.so* -> ./lib
```
In this case the `imports` section works correctly.

**Comment by ericLemanissier** [comment]
I'm not confident on this one, [conan docs](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#requires) say that `a dependency can be declared as private if it is going to be fully embedded and hidden from consumers of the package`. if the user decides to use option libfoo:shared=True, then the dependency is not fully embedded, so it looks like an unsupported combination.
What improvement do you want to obtain by using private requirements?

**Comment by rikdev** [comment]
I'm using Qt, FreeType, and LibPNG libraries in my program. But the versions of the FreeType and LibPNG libraries in my program are different from those used in Qt. Since Qt fully encapsulates third-party libraries this was not a problem for me. But when I tried to switch to Conan, I got a version conflict for these libraries. I tried to fix this problem by using private requirements.

**Comment by ericLemanissier** [comment]
There is a failure to build all shared configuration (windows/linux/macos)
```
conans.errors.ConanException: Conflict in mysql-connector-c/6.1.11@bincrafters/stable
    Requirement OpenSSL/1.0.2s@conan/stable conflicts with already defined OpenSSL/1.1.1c@conan/stable
    To change it, override it in your base requirements
```
https://ci.appveyor.com/project/bincrafters/conan-qt/builds/27014473/job/m953um67j8ga5uja
I'm not sure to understand why such conflict did not happen when openssl was a public requirement, and why it happens now that openssl is private. Do you have an idea ?

**Comment by thorntonryan** [comment]
I think I just ran into this issue as well. 

I built Qt with `shared=True` but the bulk of Qt's requirements are static libraries and show up in the package_id:
```
conan search qt/5.14.1@bincrafters/stable
Existing packages for recipe qt/5.14.1@bincrafters/stable:

    Package_ID: 7de8df7bd96d3c7061accc852e8e52dc253404c3
        [options]
...
        [settings]
...
        [requires]
            bzip2/1.0.8:2b61393137aa0ebaed1ff61cdb700806ae5daa29
            double-conversion/3.1.5:d3c57f1b4faa70d5d60e94d8531667d77c8367ac
            freetype/2.10.1:98ef3e7ee1d4e6bcbb6f0bffd886b31edbef5b9c
            gettext/0.20.1@bincrafters/stable:b781fae73cc0e6e52abf2079f00ae14ff4473189
            glib/2.58.3@bincrafters/stable:21497e60b29b6922ddeb40f6beec7309fd776f34
            harfbuzz/2.6.2@bincrafters/stable:ff707baf3b696b7faf47b44bab2ff6a320fb24e1
            libelf/0.8.13:d3c57f1b4faa70d5d60e94d8531667d77c8367ac
            libffi/3.2.1:d3c57f1b4faa70d5d60e94d8531667d77c8367ac
            libiconv/1.15:d3c57f1b4faa70d5d60e94d8531667d77c8367ac
            libjpeg/9c:d3c57f1b4faa70d5d60e94d8531667d77c8367ac
            libpng/1.6.37:6a5d4b2ef85454974bd2a1e5c930f518b8a8128a
            libpq/11.5:4db5b0dc0825f862c534da19be234d29302407da
            libxml2/2.9.9:f10fb92292ef72a516e49371e86e595cb7cd3f6e
            openssl/1.1.1d:6a5d4b2ef85454974bd2a1e5c930f518b8a8128a
            pcre/8.41:802dbd746ac78a3a56a10cf5ea90815aa9288d23
            sqlite3/3.29.0:5dd47f498e7b51a3a0671d8575f5f1f8c6ed746c
            zlib/1.2.11:d3c57f1b4faa70d5d60e94d8531667d77c8367ac
        Outdated from recipe: False
```

Like @rikdev mentioned, Qt fully encapsulates these libraries and if `shared=True` has already statically linked these libraries into the resulting binary. I don't think these requirements should be imposed on downstream consumers.

Is this PR held up on the build failure or is the approach lacking in some way?

**Comment by ericLemanissier** [comment]
I don't feel confident with this PR, especially with conan refusing this kind of change on conan-center-index: https://github.com/conan-io/conan-center-index/pull/179#discussion_r331951121
You should be able to override qt's dependencies, what kind of error do you get?

**Comment by thorntonryan** [comment]
> I don't feel confident with this PR, especially with conan refusing this kind of change on conan-center-index: [conan-io/conan-center-index#179 (comment)](https://github.com/conan-io/conan-center-index/pull/179#discussion_r331951121)
> You should be able to override qt's dependencies, what kind of error do you get?

Yeah, I found that comment from @memsharded and was wondering the same. 

> You should be able to override qt's dependencies, what kind of error do you get?

It's not so much an issue overriding Qt's dependencies, I can build the qt package just fine\*. It's just that these static libs then leak into the resulting package's ID, which affects downstream consumers.

If I upload my prebuilt qt package binaries, my coworkers are still required to download and/or build all these static libs that they don't even need. 

_\*Once I work around a few unrelated bugs reported elsewhere_

**Comment by thorntonryan** [comment]
I'm currently working to merge in @rikdev 's changes into 5.14.1/stable and re-run the build to see what happens.

**Comment by ericLemanissier** [comment]
It's true that you have to download/build all static requirements, even qt's binary is still here. On the other hand, the linker should discard all the unused static libraries. Do you have symbols from these static libs inside your executable ?

**Comment by thorntonryan** [comment]
> Do you have symbols from these static libs inside your executable ?

No -- my app doesn't consume any of Qt's static libs for any reason. Qt hides these as implementation details and it's not leaked into Qt's API.

**Comment by thorntonryan** [comment]
Okay, merging this branch into 5.14.1/stable still builds.

Thinking about this some, I think we need to tweak the pull slightly. Something along the lines of:

```diff
-self.requires("OpenSSL/1.1.1c@conan/stable", private=self.options.shared)
+self.requires("OpenSSL/1.1.1c@conan/stable", private=self.options.shared and not self.options["OpenSSL"].shared)
```
_`self.options.shared` is not sufficient. But I think `self.options.shared and not self.options["OpenSSL"].shared` might be. I wonder if that might better address the concerns raised in https://github.com/conan-io/conan-center-index/pull/179#discussion_r331951121_

I think the goal should be:

Qt | Supporting Lib | Result
---|------------------|--------
shared = False | shared = [False, True] | lib should show up as a public requirement 
shared = True | shared = True | lib should show up as a public requirement
shared = True | shared = False | lib should show up as a *private* requirement

If Qt is static or the supporting library is shared, then the supporting library should be a public requirement and participate in all transitive dependency conflict resolution, etc.

However, if Qt is *shared* and the supporting library is *static*, then Qt shouldn't impose static linking of these supporting libraries on downstream consumers. Here, *private* requirements seems perfectly appropriate.

Additionally, if Qt is *shared* and the supporting library is *static*, then the supporting library's contribution to the package_id should be `package_revision_mode`. See [here](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=package_revision_mode#versioning-schema)

For example, you could have a scenario such that a shared Qt statically linked to libFoo/1.0.0 and downstream consumers explicitly require/override to another version like libFoo/1.1.0 (e.g. pick up security patches, etc.). 

In such a scenario, we want to ensure that our downstream consumer *doesn't get* the unpatched static library baked into Qt and instead reject that package as viable.

To cover that case, I think we just need to add a call to [self.info.shared_library_package_id()](https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-info-shared-library-package-id)
```diff
def package_id(self):
        # Backwards compatibility for cross_compile to not affect package_id
        # for people who don't use the `device` option
        self.info.options.cross_compile = None
        del self.info.options.sysroot
+
+       self.info.shared_library_package_id()
```

**Comment by ericLemanissier** [comment]
I did not know about shared_library_package_id, thanks for the information ! [Only 3 recipes (on the same repo) seem to use it on github](https://github.com/search?l=Python&q=shared_library_package_id&type=Code). This is quite surprising for something which looks like a good default. I have to dig dipper on this.

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new pull request in the Conan Center Index repository.

Thanks!

https://conan.io/center/qt

**Pull request closed without merging**
