### PR TITLE
Adapting the recipe to build with emscripten

### PR DESCRIPTION
**Pull request by anagno**
Hello Everyone,

I tried to compile qt6 and these are the necessary changes for building it.

Some of the necessary changes are pushing conan to the limit. 
Mainly to cross compile qt6 you need to have a native build already. But that is 
not the only problem. We also have to package some of the native tools, so the clients
can also compile the source code (e.g. moc, etc). How are we supposed to deal with this?
The solution I have here probably is not the best :) 

Kind regards,

Vasileios

P.S.: The profiles I used:

linux_build profile:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

wasm_host profile:
```
[settings]
os=Emscripten
arch=x86
build_type=Release
compiler=clang
compiler.version=11
compiler.cppstd=17
compiler.libcxx=libstdc++11

[build_requires]
emsdk_installer/1.39.13@bincrafters/stable

[options]
qt:with_vulkan=False
qt:openssl=False
qt:with_glib=False
qt:with_fontconfig=False
qt:with_icu=False
qt:with_harfbuzz=False
qt:with_libjpeg=False
qt:with_libpng=False
qt:with_sqlite3=False
qt:with_mysql=False
qt:with_pq=False
qt:with_odbc=False
qt:with_libalsa=False
qt:with_openal=False
qt:with_zstd=False
#qt:multiconfiguration=False


# necassary packages 
qt:with_pcre2=True
# widgets need freetype, which needs brotli that does not build
#qt:with_freetype=False
freetype:with_brotli=False

# conan create --profile:build=linux_build --profile:host=wasm_host . qt/6.0.0@bincrafters/stable --build=missing --keep-source
```

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Thanks ! It seems a little early to integrate this patch, because there are still some revisions on https://codereview.qt-project.org/c/qt/qtbase/+/313243, and the feature is scheduled for qt 6.2, which is nto yet scheduled yet, but should probably be released at the end of the year.
Regarding the build requirement on qt, I think it would be better if we had a package which builds only qtbase and qttools. That would avoid to have to build "everything needed" twice. We would need to modularize the recipe, which is probably possible since qt 6.0.0.

**Comment by anagno** [comment]
You are absolute right :) I was just playing with the wasm and qt :)
Even if we break the recipe in 2 recipes, we still have the same problem. When we cross compile qt we need the native tools. So in case of cross compilation we need to be able to propagate the qttools for the build context and not for the host context. Is that even possible? Am I missing something ?

**Comment by ericLemanissier** [comment]
I think it should be ok with a build requirement yes, but I'm not sure if a package can be a build_requirement of itself. This has to be tested.

**Comment by anagno** [comment]
In this specific case, it did not seem to cause problems. I was able to use qt as build requires. It is not an infinite loop, because it only happens in the cross compilation. But probably it is safer to break it in 2 packages :)

Are build_requires propagated to the client? So, in this example, if I do not pack the qttools (which are for a completely different architecture in comparison to the host context), the test_package will not build.

**Comment by ericLemanissier** [comment]
no, build_requirements are not propagated, so the test recipe whould have to build_require qt too if it's cross compilation scenario

**Pull request closed without merging**
