### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by Croydon**

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Some of the fails can probably be solved by setting CONAN_DOCKER_32_IMAGES environment variable.
What is the configuration running the builds (distribution and docker version) ?

**Comment by Croydon** [comment]
I have set CONAN_DOCKER_32_IMAGES to True already. Does it need a specific value or just to be defined?

Since I have done this before the run either the value is wrong or this isn't the cause of the errors.

Dist is Ubuntu 16.04, Docker version no idea.

**Comment by Croydon** [comment]
Do you have any idea why Apple Clang 10 is failing? It somehow only detects Apple Clang 9.1

The setup should be fine in general however, as my test with ogg succeeded https://dev.azure.com/cr0ydon/conan-ogg/_build/results?buildId=46&view=logs

**Comment by Croydon** [comment]
> Docker (Docker version 18.06.1-ce, build e68fc7a)
Docker Compose (docker-compose version 1.22.0, build f46880fe)

https://github.com/Microsoft/azure-pipelines-image-generation/blob/e9ee71def1b5a54d7d42fe4415c1ccd32346183b/images/linux/Ubuntu1604-README.md

**Comment by bilke** [comment]
@Croydon You can use `xcode-select` to set another Apple Clang, see e.g.:

https://github.com/bilke/conan-qt-bincrafters/blob/stable/5.11.2/azure-pipelines.yml#L27-L39

**Comment by Croydon** [comment]
That is exactly what we are already doing https://github.com/bincrafters/conan-qt/blob/azure-pipelines/azure-pipelines.yml#L124

**Comment by ericLemanissier** [comment]
CONAN_DOCKER_32_IMAGES is ok, I had only checked the 2 first builds which did not seem to have it.
failing linux builds (gcc and clang) with error message `Could not find qmake spec ''` should probably be fixed by https://github.com/bilke/conan-qt-bincrafters/commit/7cfc4ad8bfc90897a1dbb5f25f1f070bd87d09fd (or waiting until qt 5.12.0 is out)

**Comment by Croydon** [comment]
I guess I misunderstood you then in the other issue. I was thinking this bug only happens on older Docker versions?

**Comment by ericLemanissier** [comment]
I thought it too, but as the problem appears again there probably another cause. looking at https://github.com/moby/moby/pull/36417#issuecomment-369266565 it looks like outdated libseccomp could also be a problem. Maybe it is what's happening.

**Pull request closed without merging**
