### PR TITLE
Add strawberry perl to windows build requirement

### PR DESCRIPTION
**Pull request by planetmarshall**
Add Strawberry Perl as a build requirement for windows. Fix for bincrafters/community#1206

### CODE REVIEW

**Comment by ericLemanissier** [comment]
thanks ! Could you test that it actually fixes the problem?

**Comment by planetmarshall** [comment]
> thanks ! Could you test that it actually fixes the problem?

It does work - the only issue is that if the client already has a (non-windows friendly) perl in the path, this won't fix the issue as the conan packages adds Strawberry Perl to the end of the Path variable.

The workaround is to temporarily move the pre-existing perl before building the package.

**Comment by ericLemanissier** [comment]
can you please retry with the standard recipe, but without pre-existing perl in path ? I think it should work without this PR.

**Comment by planetmarshall** [comment]
> can you please retry with the standard recipe, but without pre-existing perl in path ? I think it should work without this PR.

It does work, yes - provided of course you already have a Windows-friendly Perl installed in the path (eg Strawberry Perl - this is the case for the Azure Pipelines agents)

**Comment by ericLemanissier** [comment]
reading https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/mimetypes/mime/generate.bat?h=5.15.1, I expect it to work also if you don't have perl in path at all

**Comment by planetmarshall** [comment]
> reading https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/mimetypes/mime/generate.bat?h=5.15.1, I expect it to work also if you don't have perl in path at all

Ah right, will take a look.

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new pull request in the Conan Center Index repository.

Thanks!

https://conan.io/center/qt

**Pull request closed without merging**
