### PR TITLE
add support for libjpeg-turbo using with_libjpeg option

### PR DESCRIPTION
**Pull request by Renari**

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Thanks ! You need to add the following line at L557: `("libjpeg-turbo", "LIBJPEG")`, so that LIBJPEG_INCDIR and LIBJPEG_LIBS is transmitted to qmake when libjpeg-turbo is used

**Comment by ericLemanissier** [comment]
Did you test locally with option `with_libjpeg=libjpeg-turbo` ? Does it work ok ?

**Comment by Renari** [comment]
I tested the build process I wasn't able to test functionality in a project that uses qt yet.

**Comment by ericLemanissier** [comment]
thanks again !

**Pull request merged**
